use cs503;
drop table if exists experiment;

CREATE TABLE experiment ( 
indexnumber INT,
experiment_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
bamFile TEXT,
fastqFTP TEXT,
experiment_alias TEXT,
experiment_accession VARCHAR(15),
broker_name TEXT,
center_name TEXT,
title TEXT,
study_name TEXT,
study_accession VARCHAR(15),
design_description TEXT,
sample_name TEXT,
sample_accession VARCHAR(15),
sample_member TEXT,
library_name TEXT,
library_strategy TEXT,
library_source TEXT,
library_selection TEXT,
library_layout TEXT,
targeted_loci TEXT,
library_construction_protocol TEXT,
spot_length INT,
adapter_spec TEXT,
read_spec TEXT,
platform TEXT,
instrument_model TEXT,
platform_parameters TEXT,
sequence_space TEXT,
base_caller TEXT,
quality_scorer TEXT,
number_of_levels TEXT,
multiplier TEXT,
qtype TEXT,
sra_link TEXT,
experiment_url_link TEXT,
xref_link TEXT,
experiment_entrez_link TEXT,
ddbj_link TEXT,
ena_link TEXT,
experiment_attribute TEXT,
submission_accession VARCHAR(15),
sradb_updated DATETIME,
unique key(experiment_accession)
);